function [infl_loc] = fcnBOUNDIND(dvenum, dvetype, fpg, matPLEX, matROTANG, matCONTROL, vecBI, ztol)
warning('on')
tol = 1e-10;

fpl = fcnGLOBSTAR(fpg - matCONTROL(dvenum,:), matROTANG(dvenum,:));

x_m = fpl(:,1);
y_m = fpl(:,2);
z_m = fpl(:,3);

idx_afx = abs(z_m) < ztol;
z_m_orig = z_m(idx_afx);
sgn = sign(z_m_orig);
sgn(sgn == 0) = 1;
z_m(idx_afx) = sgn.*ztol;

%% Checking state of field point with relation to element surface
margin_edge = 1e-10;

xi_1 = permute(matPLEX(1,1,dvenum),[3 2 1]);
xi_2 = permute(matPLEX(2,1,dvenum),[3 2 1]);
xi_3 = permute(matPLEX(3,1,dvenum),[3 2 1]);

eta_1 = permute(matPLEX(1,2,dvenum),[3 2 1]);
eta_2 = permute(matPLEX(2,2,dvenum),[3 2 1]);
eta_3 = permute(matPLEX(3,2,dvenum),[3 2 1]);

idx_flp = xi_3 < xi_1; % Flipping influence of elements that need a good flippin
if any(abs(xi_2 - xi_3) < margin_edge & abs(xi_1 - xi_2) > margin_edge)
    disp('Issue in element orientation in HDVEIND.');
end

% Checking which elements are on the element
C = (eta_3 - eta_2)./(xi_3 - xi_2);
D_LE = eta_2 - ((xi_2.*(eta_3 - eta_2))./(xi_3 - xi_2));
E = (eta_3 - eta_1)./(xi_3 - xi_1);
D_TE = eta_1 - ((xi_1.*(eta_3 - eta_1))./(xi_3 - xi_1));

%% Bound induction

if any(vecBI)    
    tmp11 = ((eta_3(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_3(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_3(vecBI) + xi_3(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2) .^ (-0.1e1 ./ 0.2e1)) .* (C(vecBI) .^ 2 .* xi_2(vecBI) .^ 2 + C(vecBI) .* (C(vecBI) .* xi_3(vecBI) + 3 .* D_LE(vecBI)) .* xi_2(vecBI) + C(vecBI) .^ 2 .* xi_3(vecBI) .^ 2 + 3 .* C(vecBI) .* D_LE(vecBI) .* xi_3(vecBI) + 3 .* D_LE(vecBI) .^ 2) .* (-xi_3(vecBI) + xi_2(vecBI)) .* (eta_2(vecBI) - eta_3(vecBI)) .* (((x_m(vecBI) - xi_3(vecBI)) .* xi_2(vecBI) + xi_3(vecBI) .^ 2 - x_m(vecBI) .* xi_3(vecBI) + (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_3(vecBI))) .* sqrt((eta_2(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_2(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_2(vecBI) + xi_2(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2)) - (-xi_2(vecBI) .^ 2 + (xi_3(vecBI) + x_m(vecBI)) .* xi_2(vecBI) - x_m(vecBI) .* xi_3(vecBI) + (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_2(vecBI))) .* sqrt((eta_3(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_3(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_3(vecBI) + xi_3(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2))) .* z_m(vecBI) .* ((eta_2(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_2(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_2(vecBI) + xi_2(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2) .^ (-0.1e1 ./ 0.2e1)) ./ ((6 .* eta_3(vecBI) .^ 2 - 12 .* y_m(vecBI) .* eta_3(vecBI) + 6 .* y_m(vecBI) .^ 2 + 6 .* z_m(vecBI) .^ 2) .* xi_2(vecBI) .^ 2 + (((12 .* y_m(vecBI) - 12 .* eta_3(vecBI)) .* eta_2(vecBI) - 12 .* y_m(vecBI) .^ 2 + 12 .* y_m(vecBI) .* eta_3(vecBI) - 12 .* z_m(vecBI) .^ 2) .* xi_3(vecBI) - 12 .* x_m(vecBI) .* (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_3(vecBI))) .* xi_2(vecBI) + (6 .* eta_2(vecBI) .^ 2 - 12 .* y_m(vecBI) .* eta_2(vecBI) + 6 .* y_m(vecBI) .^ 2 + 6 .* z_m(vecBI) .^ 2) .* xi_3(vecBI) .^ 2 + 12 .* (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_2(vecBI)) .* x_m(vecBI) .* xi_3(vecBI) + 6 .* (eta_2(vecBI) - eta_3(vecBI)) .^ 2 .* (x_m(vecBI) .^ 2 + z_m(vecBI) .^ 2));
    tmp12 = ((eta_3(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_3(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_3(vecBI) + xi_3(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2) .^ (-0.1e1 ./ 0.2e1)) .* (C(vecBI) .* xi_2(vecBI) + C(vecBI) .* xi_3(vecBI) + 2 .* D_LE(vecBI)) .* (-xi_3(vecBI) + xi_2(vecBI)) .* (eta_2(vecBI) - eta_3(vecBI)) .* (((x_m(vecBI) - xi_3(vecBI)) .* xi_2(vecBI) + xi_3(vecBI) .^ 2 - x_m(vecBI) .* xi_3(vecBI) + (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_3(vecBI))) .* sqrt((eta_2(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_2(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_2(vecBI) + xi_2(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2)) - (-xi_2(vecBI) .^ 2 + (xi_3(vecBI) + x_m(vecBI)) .* xi_2(vecBI) - x_m(vecBI) .* xi_3(vecBI) + (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_2(vecBI))) .* sqrt((eta_3(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_3(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_3(vecBI) + xi_3(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2))) .* z_m(vecBI) .* ((eta_2(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_2(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_2(vecBI) + xi_2(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2) .^ (-0.1e1 ./ 0.2e1)) ./ ((2 .* eta_3(vecBI) .^ 2 - 4 .* y_m(vecBI) .* eta_3(vecBI) + 2 .* y_m(vecBI) .^ 2 + 2 .* z_m(vecBI) .^ 2) .* xi_2(vecBI) .^ 2 + (((4 .* y_m(vecBI) - 4 .* eta_3(vecBI)) .* eta_2(vecBI) - 4 .* y_m(vecBI) .^ 2 + 4 .* y_m(vecBI) .* eta_3(vecBI) - 4 .* z_m(vecBI) .^ 2) .* xi_3(vecBI) - 4 .* x_m(vecBI) .* (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_3(vecBI))) .* xi_2(vecBI) + (2 .* eta_2(vecBI) .^ 2 - 4 .* y_m(vecBI) .* eta_2(vecBI) + 2 .* y_m(vecBI) .^ 2 + 2 .* z_m(vecBI) .^ 2) .* xi_3(vecBI) .^ 2 + 4 .* (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_2(vecBI)) .* x_m(vecBI) .* xi_3(vecBI) + 2 .* (eta_2(vecBI) - eta_3(vecBI)) .^ 2 .* (x_m(vecBI) .^ 2 + z_m(vecBI) .^ 2));
    tmp13 = -(-xi_3(vecBI) + xi_2(vecBI)) .* (eta_2(vecBI) - eta_3(vecBI)) .* (xi_2(vecBI) .^ 2 + xi_3(vecBI) .* xi_2(vecBI) + xi_3(vecBI) .^ 2) .* ((eta_3(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_3(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_3(vecBI) + xi_3(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2) .^ (-0.1e1 ./ 0.2e1)) .* z_m(vecBI) .* (((-y_m(vecBI) + eta_3(vecBI)) .* eta_2(vecBI) - eta_3(vecBI) .^ 2 + y_m(vecBI) .* eta_3(vecBI) - (-xi_3(vecBI) + xi_2(vecBI)) .* (x_m(vecBI) - xi_3(vecBI))) .* sqrt((eta_2(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_2(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_2(vecBI) + xi_2(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2)) + (-eta_2(vecBI) .^ 2 + (y_m(vecBI) + eta_3(vecBI)) .* eta_2(vecBI) - y_m(vecBI) .* eta_3(vecBI) + (-xi_3(vecBI) + xi_2(vecBI)) .* (x_m(vecBI) - xi_2(vecBI))) .* sqrt((eta_3(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_3(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_3(vecBI) + xi_3(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2))) .* ((eta_2(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_2(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_2(vecBI) + xi_2(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2) .^ (-0.1e1 ./ 0.2e1)) ./ ((6 .* x_m(vecBI) .^ 2 - 12 .* x_m(vecBI) .* xi_3(vecBI) + 6 .* xi_3(vecBI) .^ 2 + 6 .* z_m(vecBI) .^ 2) .* eta_2(vecBI) .^ 2 + (((12 .* x_m(vecBI) - 12 .* xi_3(vecBI)) .* xi_2(vecBI) - 12 .* x_m(vecBI) .^ 2 + 12 .* x_m(vecBI) .* xi_3(vecBI) - 12 .* z_m(vecBI) .^ 2) .* eta_3(vecBI) - 12 .* y_m(vecBI) .* (-xi_3(vecBI) + xi_2(vecBI)) .* (x_m(vecBI) - xi_3(vecBI))) .* eta_2(vecBI) + (6 .* x_m(vecBI) .^ 2 - 12 .* x_m(vecBI) .* xi_2(vecBI) + 6 .* xi_2(vecBI) .^ 2 + 6 .* z_m(vecBI) .^ 2) .* eta_3(vecBI) .^ 2 + 12 .* y_m(vecBI) .* (-xi_3(vecBI) + xi_2(vecBI)) .* (x_m(vecBI) - xi_2(vecBI)) .* eta_3(vecBI) + 6 .* (-xi_3(vecBI) + xi_2(vecBI)) .^ 2 .* (y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2));
    tmp14 = -(-xi_3(vecBI) + xi_2(vecBI)) .* (eta_2(vecBI) - eta_3(vecBI)) .* (xi_2(vecBI) + xi_3(vecBI)) .* ((eta_3(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_3(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_3(vecBI) + xi_3(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2) .^ (-0.1e1 ./ 0.2e1)) .* z_m(vecBI) .* (((-y_m(vecBI) + eta_3(vecBI)) .* eta_2(vecBI) - eta_3(vecBI) .^ 2 + y_m(vecBI) .* eta_3(vecBI) - (-xi_3(vecBI) + xi_2(vecBI)) .* (x_m(vecBI) - xi_3(vecBI))) .* sqrt((eta_2(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_2(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_2(vecBI) + xi_2(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2)) + (-eta_2(vecBI) .^ 2 + (y_m(vecBI) + eta_3(vecBI)) .* eta_2(vecBI) - y_m(vecBI) .* eta_3(vecBI) + (-xi_3(vecBI) + xi_2(vecBI)) .* (x_m(vecBI) - xi_2(vecBI))) .* sqrt((eta_3(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_3(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_3(vecBI) + xi_3(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2))) .* ((eta_2(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_2(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_2(vecBI) + xi_2(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2) .^ (-0.1e1 ./ 0.2e1)) ./ ((2 .* x_m(vecBI) .^ 2 - 4 .* x_m(vecBI) .* xi_3(vecBI) + 2 .* xi_3(vecBI) .^ 2 + 2 .* z_m(vecBI) .^ 2) .* eta_2(vecBI) .^ 2 + (((-4 .* xi_3(vecBI) + 4 .* x_m(vecBI)) .* xi_2(vecBI) - 4 .* z_m(vecBI) .^ 2 + 4 .* x_m(vecBI) .* xi_3(vecBI) - 4 .* x_m(vecBI) .^ 2) .* eta_3(vecBI) - 4 .* y_m(vecBI) .* (-xi_3(vecBI) + xi_2(vecBI)) .* (x_m(vecBI) - xi_3(vecBI))) .* eta_2(vecBI) + (2 .* x_m(vecBI) .^ 2 - 4 .* x_m(vecBI) .* xi_2(vecBI) + 2 .* xi_2(vecBI) .^ 2 + 2 .* z_m(vecBI) .^ 2) .* eta_3(vecBI) .^ 2 + 4 .* y_m(vecBI) .* (-xi_3(vecBI) + xi_2(vecBI)) .* (x_m(vecBI) - xi_2(vecBI)) .* eta_3(vecBI) + 2 .* (-xi_3(vecBI) + xi_2(vecBI)) .^ 2 .* (y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2));
    tmp15 = 0.2e1 .* ((eta_3(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_3(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_3(vecBI) + xi_3(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2) .^ (-0.1e1 ./ 0.2e1)) .* (-xi_3(vecBI) + xi_2(vecBI)) .* (eta_2(vecBI) - eta_3(vecBI)) .* ((C(vecBI) .* xi_2(vecBI) .^ 2) + ((C(vecBI) .* xi_3(vecBI)) + 0.3e1 ./ 0.2e1 .* D_LE(vecBI)) .* xi_2(vecBI) + xi_3(vecBI) .* ((C(vecBI) .* xi_3(vecBI)) + 0.3e1 ./ 0.2e1 .* D_LE(vecBI))) .* (((x_m(vecBI) - xi_3(vecBI)) .* xi_2(vecBI) + xi_3(vecBI) .^ 2 - x_m(vecBI) .* xi_3(vecBI) + (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_3(vecBI))) .* sqrt((eta_2(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_2(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_2(vecBI) + xi_2(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2)) - (-xi_2(vecBI) .^ 2 + (xi_3(vecBI) + x_m(vecBI)) .* xi_2(vecBI) - x_m(vecBI) .* xi_3(vecBI) + (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_2(vecBI))) .* sqrt((eta_3(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_3(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_3(vecBI) + xi_3(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2))) .* z_m(vecBI) .* ((eta_2(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_2(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_2(vecBI) + xi_2(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2) .^ (-0.1e1 ./ 0.2e1)) ./ ((6 .* eta_3(vecBI) .^ 2 - 12 .* y_m(vecBI) .* eta_3(vecBI) + 6 .* y_m(vecBI) .^ 2 + 6 .* z_m(vecBI) .^ 2) .* xi_2(vecBI) .^ 2 + (((12 .* y_m(vecBI) - 12 .* eta_3(vecBI)) .* eta_2(vecBI) - 12 .* y_m(vecBI) .^ 2 + 12 .* y_m(vecBI) .* eta_3(vecBI) - 12 .* z_m(vecBI) .^ 2) .* xi_3(vecBI) - 12 .* x_m(vecBI) .* (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_3(vecBI))) .* xi_2(vecBI) + (6 .* eta_2(vecBI) .^ 2 - 12 .* y_m(vecBI) .* eta_2(vecBI) + 6 .* y_m(vecBI) .^ 2 + 6 .* z_m(vecBI) .^ 2) .* xi_3(vecBI) .^ 2 + 12 .* (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_2(vecBI)) .* x_m(vecBI) .* xi_3(vecBI) + 6 .* (eta_2(vecBI) - eta_3(vecBI)) .^ 2 .* (x_m(vecBI) .^ 2 + z_m(vecBI) .^ 2));
    tmp16 = -(-xi_3(vecBI) + xi_2(vecBI)) .* (eta_2(vecBI) - eta_3(vecBI)) .* ((eta_3(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_3(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_3(vecBI) + xi_3(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2) .^ (-0.1e1 ./ 0.2e1)) .* z_m(vecBI) .* (((-y_m(vecBI) + eta_3(vecBI)) .* eta_2(vecBI) - eta_3(vecBI) .^ 2 + y_m(vecBI) .* eta_3(vecBI) - (-xi_3(vecBI) + xi_2(vecBI)) .* (x_m(vecBI) - xi_3(vecBI))) .* sqrt((eta_2(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_2(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_2(vecBI) + xi_2(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2)) + (-eta_2(vecBI) .^ 2 + (y_m(vecBI) + eta_3(vecBI)) .* eta_2(vecBI) - y_m(vecBI) .* eta_3(vecBI) + (-xi_3(vecBI) + xi_2(vecBI)) .* (x_m(vecBI) - xi_2(vecBI))) .* sqrt((eta_3(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_3(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_3(vecBI) + xi_3(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2))) .* ((eta_2(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_2(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_2(vecBI) + xi_2(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2) .^ (-0.1e1 ./ 0.2e1)) ./ ((x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_3(vecBI) + xi_3(vecBI) .^ 2 + z_m(vecBI) .^ 2) .* eta_2(vecBI) .^ 2 + (((2 .* x_m(vecBI) - 2 .* xi_3(vecBI)) .* xi_2(vecBI) - 2 .* x_m(vecBI) .^ 2 + 2 .* x_m(vecBI) .* xi_3(vecBI) - 2 .* z_m(vecBI) .^ 2) .* eta_3(vecBI) - 2 .* y_m(vecBI) .* (-xi_3(vecBI) + xi_2(vecBI)) .* (x_m(vecBI) - xi_3(vecBI))) .* eta_2(vecBI) + (x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_2(vecBI) + xi_2(vecBI) .^ 2 + z_m(vecBI) .^ 2) .* eta_3(vecBI) .^ 2 + 2 .* y_m(vecBI) .* (-xi_3(vecBI) + xi_2(vecBI)) .* (x_m(vecBI) - xi_2(vecBI)) .* eta_3(vecBI) + (-xi_3(vecBI) + xi_2(vecBI)) .^ 2 .* (y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2));
    tmp21 = -((eta_3(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_3(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_3(vecBI) + xi_3(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2) .^ (-0.1e1 ./ 0.2e1)) .* (C(vecBI) .^ 2 .* xi_2(vecBI) .^ 2 + C(vecBI) .* (C(vecBI) .* xi_3(vecBI) + 3 .* D_LE(vecBI)) .* xi_2(vecBI) + C(vecBI) .^ 2 .* xi_3(vecBI) .^ 2 + 3 .* C(vecBI) .* D_LE(vecBI) .* xi_3(vecBI) + 3 .* D_LE(vecBI) .^ 2) .* ((-xi_3(vecBI) + xi_2(vecBI)) .^ 2) .* (((x_m(vecBI) - xi_3(vecBI)) .* xi_2(vecBI) + xi_3(vecBI) .^ 2 - x_m(vecBI) .* xi_3(vecBI) + (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_3(vecBI))) .* sqrt((eta_2(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_2(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_2(vecBI) + xi_2(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2)) - (-xi_2(vecBI) .^ 2 + (xi_3(vecBI) + x_m(vecBI)) .* xi_2(vecBI) - x_m(vecBI) .* xi_3(vecBI) + (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_2(vecBI))) .* sqrt((eta_3(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_3(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_3(vecBI) + xi_3(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2))) .* z_m(vecBI) .* ((eta_2(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_2(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_2(vecBI) + xi_2(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2) .^ (-0.1e1 ./ 0.2e1)) ./ ((6 .* eta_3(vecBI) .^ 2 - 12 .* y_m(vecBI) .* eta_3(vecBI) + 6 .* y_m(vecBI) .^ 2 + 6 .* z_m(vecBI) .^ 2) .* xi_2(vecBI) .^ 2 + (((12 .* y_m(vecBI) - 12 .* eta_3(vecBI)) .* eta_2(vecBI) - 12 .* y_m(vecBI) .^ 2 + 12 .* y_m(vecBI) .* eta_3(vecBI) - 12 .* z_m(vecBI) .^ 2) .* xi_3(vecBI) - 12 .* x_m(vecBI) .* (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_3(vecBI))) .* xi_2(vecBI) + (6 .* eta_2(vecBI) .^ 2 - 12 .* y_m(vecBI) .* eta_2(vecBI) + 6 .* y_m(vecBI) .^ 2 + 6 .* z_m(vecBI) .^ 2) .* xi_3(vecBI) .^ 2 + 12 .* (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_2(vecBI)) .* x_m(vecBI) .* xi_3(vecBI) + 6 .* (eta_2(vecBI) - eta_3(vecBI)) .^ 2 .* (x_m(vecBI) .^ 2 + z_m(vecBI) .^ 2));
    tmp22 = -((eta_3(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_3(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_3(vecBI) + xi_3(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2) .^ (-0.1e1 ./ 0.2e1)) .* (C(vecBI) .* xi_2(vecBI) + C(vecBI) .* xi_3(vecBI) + 2 .* D_LE(vecBI)) .* ((-xi_3(vecBI) + xi_2(vecBI)) .^ 2) .* (((x_m(vecBI) - xi_3(vecBI)) .* xi_2(vecBI) + xi_3(vecBI) .^ 2 - x_m(vecBI) .* xi_3(vecBI) + (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_3(vecBI))) .* sqrt((eta_2(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_2(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_2(vecBI) + xi_2(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2)) - (-xi_2(vecBI) .^ 2 + (xi_3(vecBI) + x_m(vecBI)) .* xi_2(vecBI) - x_m(vecBI) .* xi_3(vecBI) + (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_2(vecBI))) .* sqrt((eta_3(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_3(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_3(vecBI) + xi_3(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2))) .* z_m(vecBI) .* ((eta_2(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_2(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_2(vecBI) + xi_2(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2) .^ (-0.1e1 ./ 0.2e1)) ./ ((2 .* eta_3(vecBI) .^ 2 - 4 .* y_m(vecBI) .* eta_3(vecBI) + 2 .* y_m(vecBI) .^ 2 + 2 .* z_m(vecBI) .^ 2) .* xi_2(vecBI) .^ 2 + (((4 .* y_m(vecBI) - 4 .* eta_3(vecBI)) .* eta_2(vecBI) - 4 .* y_m(vecBI) .^ 2 + 4 .* y_m(vecBI) .* eta_3(vecBI) - 4 .* z_m(vecBI) .^ 2) .* xi_3(vecBI) - 4 .* x_m(vecBI) .* (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_3(vecBI))) .* xi_2(vecBI) + (2 .* eta_2(vecBI) .^ 2 - 4 .* y_m(vecBI) .* eta_2(vecBI) + 2 .* y_m(vecBI) .^ 2 + 2 .* z_m(vecBI) .^ 2) .* xi_3(vecBI) .^ 2 + 4 .* (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_2(vecBI)) .* x_m(vecBI) .* xi_3(vecBI) + 2 .* (eta_2(vecBI) - eta_3(vecBI)) .^ 2 .* (x_m(vecBI) .^ 2 + z_m(vecBI) .^ 2));
    tmp23 = ((-xi_3(vecBI) + xi_2(vecBI)) .^ 2) .* (xi_2(vecBI) .^ 2 + xi_2(vecBI) .* xi_3(vecBI) + xi_3(vecBI) .^ 2) .* ((eta_3(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_3(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_3(vecBI) + xi_3(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2) .^ (-0.1e1 ./ 0.2e1)) .* z_m(vecBI) .* (((xi_3(vecBI) - x_m(vecBI)) .* xi_2(vecBI) - xi_3(vecBI) .^ 2 + x_m(vecBI) .* xi_3(vecBI) - (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_3(vecBI))) .* sqrt((eta_2(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_2(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_2(vecBI) + xi_2(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2)) + (-xi_2(vecBI) .^ 2 + (xi_3(vecBI) + x_m(vecBI)) .* xi_2(vecBI) - x_m(vecBI) .* xi_3(vecBI) + (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_2(vecBI))) .* sqrt((eta_3(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_3(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_3(vecBI) + xi_3(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2))) .* ((eta_2(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_2(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_2(vecBI) + xi_2(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2) .^ (-0.1e1 ./ 0.2e1)) ./ ((6 .* eta_3(vecBI) .^ 2 - 12 .* y_m(vecBI) .* eta_3(vecBI) + 6 .* y_m(vecBI) .^ 2 + 6 .* z_m(vecBI) .^ 2) .* xi_2(vecBI) .^ 2 + (((12 .* y_m(vecBI) - 12 .* eta_3(vecBI)) .* eta_2(vecBI) - 12 .* y_m(vecBI) .^ 2 + 12 .* y_m(vecBI) .* eta_3(vecBI) - 12 .* z_m(vecBI) .^ 2) .* xi_3(vecBI) - 12 .* x_m(vecBI) .* (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_3(vecBI))) .* xi_2(vecBI) + (6 .* eta_2(vecBI) .^ 2 - 12 .* y_m(vecBI) .* eta_2(vecBI) + 6 .* y_m(vecBI) .^ 2 + 6 .* z_m(vecBI) .^ 2) .* xi_3(vecBI) .^ 2 + 12 .* (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_2(vecBI)) .* x_m(vecBI) .* xi_3(vecBI) + 6 .* (eta_2(vecBI) - eta_3(vecBI)) .^ 2 .* (x_m(vecBI) .^ 2 + z_m(vecBI) .^ 2));
    tmp24 = ((-xi_3(vecBI) + xi_2(vecBI)) .^ 2) .* (xi_2(vecBI) + xi_3(vecBI)) .* ((eta_3(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_3(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_3(vecBI) + xi_3(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2) .^ (-0.1e1 ./ 0.2e1)) .* z_m(vecBI) .* (((xi_3(vecBI) - x_m(vecBI)) .* xi_2(vecBI) - xi_3(vecBI) .^ 2 + x_m(vecBI) .* xi_3(vecBI) - (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_3(vecBI))) .* sqrt((eta_2(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_2(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_2(vecBI) + xi_2(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2)) + (-xi_2(vecBI) .^ 2 + (xi_3(vecBI) + x_m(vecBI)) .* xi_2(vecBI) - x_m(vecBI) .* xi_3(vecBI) + (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_2(vecBI))) .* sqrt((eta_3(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_3(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_3(vecBI) + xi_3(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2))) .* ((eta_2(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_2(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_2(vecBI) + xi_2(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2) .^ (-0.1e1 ./ 0.2e1)) ./ ((2 .* eta_3(vecBI) .^ 2 - 4 .* y_m(vecBI) .* eta_3(vecBI) + 2 .* y_m(vecBI) .^ 2 + 2 .* z_m(vecBI) .^ 2) .* xi_2(vecBI) .^ 2 + (((4 .* y_m(vecBI) - 4 .* eta_3(vecBI)) .* eta_2(vecBI) - 4 .* y_m(vecBI) .^ 2 + 4 .* y_m(vecBI) .* eta_3(vecBI) - 4 .* z_m(vecBI) .^ 2) .* xi_3(vecBI) - 4 .* x_m(vecBI) .* (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_3(vecBI))) .* xi_2(vecBI) + (2 .* eta_2(vecBI) .^ 2 - 4 .* y_m(vecBI) .* eta_2(vecBI) + 2 .* y_m(vecBI) .^ 2 + 2 .* z_m(vecBI) .^ 2) .* xi_3(vecBI) .^ 2 + 4 .* (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_2(vecBI)) .* x_m(vecBI) .* xi_3(vecBI) + 2 .* (eta_2(vecBI) - eta_3(vecBI)) .^ 2 .* (x_m(vecBI) .^ 2 + z_m(vecBI) .^ 2));
    tmp25 = -0.2e1 .* ((eta_3(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_3(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_3(vecBI) + xi_3(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2) .^ (-0.1e1 ./ 0.2e1)) .* ((-xi_3(vecBI) + xi_2(vecBI)) .^ 2) .* ((C(vecBI) .* xi_2(vecBI) .^ 2) + ((C(vecBI) .* xi_3(vecBI)) + 0.3e1 ./ 0.2e1 .* D_LE(vecBI)) .* xi_2(vecBI) + xi_3(vecBI) .* ((C(vecBI) .* xi_3(vecBI)) + 0.3e1 ./ 0.2e1 .* D_LE(vecBI))) .* (((x_m(vecBI) - xi_3(vecBI)) .* xi_2(vecBI) + xi_3(vecBI) .^ 2 - x_m(vecBI) .* xi_3(vecBI) + (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_3(vecBI))) .* sqrt((eta_2(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_2(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_2(vecBI) + xi_2(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2)) - (-xi_2(vecBI) .^ 2 + (xi_3(vecBI) + x_m(vecBI)) .* xi_2(vecBI) - x_m(vecBI) .* xi_3(vecBI) + (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_2(vecBI))) .* sqrt((eta_3(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_3(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_3(vecBI) + xi_3(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2))) .* z_m(vecBI) .* ((eta_2(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_2(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_2(vecBI) + xi_2(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2) .^ (-0.1e1 ./ 0.2e1)) ./ ((6 .* eta_3(vecBI) .^ 2 - 12 .* y_m(vecBI) .* eta_3(vecBI) + 6 .* y_m(vecBI) .^ 2 + 6 .* z_m(vecBI) .^ 2) .* xi_2(vecBI) .^ 2 + (((12 .* y_m(vecBI) - 12 .* eta_3(vecBI)) .* eta_2(vecBI) - 12 .* y_m(vecBI) .^ 2 + 12 .* y_m(vecBI) .* eta_3(vecBI) - 12 .* z_m(vecBI) .^ 2) .* xi_3(vecBI) - 12 .* x_m(vecBI) .* (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_3(vecBI))) .* xi_2(vecBI) + (6 .* eta_2(vecBI) .^ 2 - 12 .* y_m(vecBI) .* eta_2(vecBI) + 6 .* y_m(vecBI) .^ 2 + 6 .* z_m(vecBI) .^ 2) .* xi_3(vecBI) .^ 2 + 12 .* (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_2(vecBI)) .* x_m(vecBI) .* xi_3(vecBI) + 6 .* (eta_2(vecBI) - eta_3(vecBI)) .^ 2 .* (x_m(vecBI) .^ 2 + z_m(vecBI) .^ 2));
    tmp26 = ((-xi_3(vecBI) + xi_2(vecBI)) .^ 2) .* ((eta_3(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_3(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_3(vecBI) + xi_3(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2) .^ (-0.1e1 ./ 0.2e1)) .* z_m(vecBI) .* (((xi_3(vecBI) - x_m(vecBI)) .* xi_2(vecBI) - xi_3(vecBI) .^ 2 + x_m(vecBI) .* xi_3(vecBI) - (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_3(vecBI))) .* sqrt((eta_2(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_2(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_2(vecBI) + xi_2(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2)) + (-xi_2(vecBI) .^ 2 + (xi_3(vecBI) + x_m(vecBI)) .* xi_2(vecBI) - x_m(vecBI) .* xi_3(vecBI) + (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_2(vecBI))) .* sqrt((eta_3(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_3(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_3(vecBI) + xi_3(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2))) .* ((eta_2(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_2(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_2(vecBI) + xi_2(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2) .^ (-0.1e1 ./ 0.2e1)) ./ ((eta_3(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_3(vecBI) + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2) .* xi_2(vecBI) .^ 2 + (((2 .* y_m(vecBI) - 2 .* eta_3(vecBI)) .* eta_2(vecBI) - 2 .* y_m(vecBI) .^ 2 + 2 .* y_m(vecBI) .* eta_3(vecBI) - 2 .* z_m(vecBI) .^ 2) .* xi_3(vecBI) - 2 .* x_m(vecBI) .* (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_3(vecBI))) .* xi_2(vecBI) + (eta_2(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_2(vecBI) + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2) .* xi_3(vecBI) .^ 2 + 2 .* (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_2(vecBI)) .* x_m(vecBI) .* xi_3(vecBI) + (eta_2(vecBI) - eta_3(vecBI)) .^ 2 .* (x_m(vecBI) .^ 2 + z_m(vecBI) .^ 2));
    tmp31 = -((eta_3(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_3(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_3(vecBI) + xi_3(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2) .^ (-0.1e1 ./ 0.2e1)) .* (C(vecBI) .^ 2 .* xi_2(vecBI) .^ 2 + C(vecBI) .* (C(vecBI) .* xi_3(vecBI) + 3 .* D_LE(vecBI)) .* xi_2(vecBI) + C(vecBI) .^ 2 .* xi_3(vecBI) .^ 2 + 3 .* C(vecBI) .* D_LE(vecBI) .* xi_3(vecBI) + 3 .* D_LE(vecBI) .^ 2) .* (-xi_3(vecBI) + xi_2(vecBI)) .* (((x_m(vecBI) - xi_3(vecBI)) .* xi_2(vecBI) + xi_3(vecBI) .^ 2 - x_m(vecBI) .* xi_3(vecBI) + (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_3(vecBI))) .* sqrt((eta_2(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_2(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_2(vecBI) + xi_2(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2)) - (-xi_2(vecBI) .^ 2 + (xi_3(vecBI) + x_m(vecBI)) .* xi_2(vecBI) - x_m(vecBI) .* xi_3(vecBI) + (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_2(vecBI))) .* sqrt((eta_3(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_3(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_3(vecBI) + xi_3(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2))) .* ((eta_2(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_2(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_2(vecBI) + xi_2(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2) .^ (-0.1e1 ./ 0.2e1)) .* ((-y_m(vecBI) + eta_3(vecBI)) .* xi_2(vecBI) + (y_m(vecBI) - eta_2(vecBI)) .* xi_3(vecBI) + x_m(vecBI) .* (eta_2(vecBI) - eta_3(vecBI))) ./ ((6 .* eta_3(vecBI) .^ 2 - 12 .* y_m(vecBI) .* eta_3(vecBI) + 6 .* y_m(vecBI) .^ 2 + 6 .* z_m(vecBI) .^ 2) .* xi_2(vecBI) .^ 2 + (((12 .* y_m(vecBI) - 12 .* eta_3(vecBI)) .* eta_2(vecBI) - 12 .* y_m(vecBI) .^ 2 + 12 .* y_m(vecBI) .* eta_3(vecBI) - 12 .* z_m(vecBI) .^ 2) .* xi_3(vecBI) - 12 .* x_m(vecBI) .* (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_3(vecBI))) .* xi_2(vecBI) + (6 .* eta_2(vecBI) .^ 2 - 12 .* y_m(vecBI) .* eta_2(vecBI) + 6 .* y_m(vecBI) .^ 2 + 6 .* z_m(vecBI) .^ 2) .* xi_3(vecBI) .^ 2 + 12 .* (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_2(vecBI)) .* x_m(vecBI) .* xi_3(vecBI) + 6 .* (eta_2(vecBI) - eta_3(vecBI)) .^ 2 .* (x_m(vecBI) .^ 2 + z_m(vecBI) .^ 2));
    tmp32 = -((eta_3(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_3(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_3(vecBI) + xi_3(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2) .^ (-0.1e1 ./ 0.2e1)) .* (C(vecBI) .* xi_2(vecBI) + C(vecBI) .* xi_3(vecBI) + 2 .* D_LE(vecBI)) .* (-xi_3(vecBI) + xi_2(vecBI)) .* (((x_m(vecBI) - xi_3(vecBI)) .* xi_2(vecBI) + xi_3(vecBI) .^ 2 - x_m(vecBI) .* xi_3(vecBI) + (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_3(vecBI))) .* sqrt((eta_2(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_2(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_2(vecBI) + xi_2(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2)) - (-xi_2(vecBI) .^ 2 + (xi_3(vecBI) + x_m(vecBI)) .* xi_2(vecBI) - x_m(vecBI) .* xi_3(vecBI) + (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_2(vecBI))) .* sqrt((eta_3(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_3(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_3(vecBI) + xi_3(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2))) .* ((eta_2(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_2(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_2(vecBI) + xi_2(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2) .^ (-0.1e1 ./ 0.2e1)) .* ((-y_m(vecBI) + eta_3(vecBI)) .* xi_2(vecBI) + (y_m(vecBI) - eta_2(vecBI)) .* xi_3(vecBI) + x_m(vecBI) .* (eta_2(vecBI) - eta_3(vecBI))) ./ ((2 .* eta_3(vecBI) .^ 2 - 4 .* y_m(vecBI) .* eta_3(vecBI) + 2 .* y_m(vecBI) .^ 2 + 2 .* z_m(vecBI) .^ 2) .* xi_2(vecBI) .^ 2 + (((4 .* y_m(vecBI) - 4 .* eta_3(vecBI)) .* eta_2(vecBI) - 4 .* y_m(vecBI) .^ 2 + 4 .* y_m(vecBI) .* eta_3(vecBI) - 4 .* z_m(vecBI) .^ 2) .* xi_3(vecBI) - 4 .* x_m(vecBI) .* (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_3(vecBI))) .* xi_2(vecBI) + (2 .* eta_2(vecBI) .^ 2 - 4 .* y_m(vecBI) .* eta_2(vecBI) + 2 .* y_m(vecBI) .^ 2 + 2 .* z_m(vecBI) .^ 2) .* xi_3(vecBI) .^ 2 + 4 .* (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_2(vecBI)) .* x_m(vecBI) .* xi_3(vecBI) + 2 .* (eta_2(vecBI) - eta_3(vecBI)) .^ 2 .* (x_m(vecBI) .^ 2 + z_m(vecBI) .^ 2));
    tmp33 = (-xi_3(vecBI) + xi_2(vecBI)) .* (xi_2(vecBI) .^ 2 + xi_3(vecBI) .* xi_2(vecBI) + xi_3(vecBI) .^ 2) .* ((-y_m(vecBI) + eta_3(vecBI)) .* xi_2(vecBI) + (y_m(vecBI) - eta_2(vecBI)) .* xi_3(vecBI) + x_m(vecBI) .* (eta_2(vecBI) - eta_3(vecBI))) .* ((eta_3(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_3(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_3(vecBI) + xi_3(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2) .^ (-0.1e1 ./ 0.2e1)) .* (((xi_3(vecBI) - x_m(vecBI)) .* xi_2(vecBI) - xi_3(vecBI) .^ 2 + x_m(vecBI) .* xi_3(vecBI) - (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_3(vecBI))) .* sqrt((eta_2(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_2(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_2(vecBI) + xi_2(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2)) + (-xi_2(vecBI) .^ 2 + (xi_3(vecBI) + x_m(vecBI)) .* xi_2(vecBI) - x_m(vecBI) .* xi_3(vecBI) + (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_2(vecBI))) .* sqrt((eta_3(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_3(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_3(vecBI) + xi_3(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2))) .* ((eta_2(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_2(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_2(vecBI) + xi_2(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2) .^ (-0.1e1 ./ 0.2e1)) ./ ((6 .* eta_3(vecBI) .^ 2 - 12 .* y_m(vecBI) .* eta_3(vecBI) + 6 .* y_m(vecBI) .^ 2 + 6 .* z_m(vecBI) .^ 2) .* xi_2(vecBI) .^ 2 + (((12 .* y_m(vecBI) - 12 .* eta_3(vecBI)) .* eta_2(vecBI) - 12 .* y_m(vecBI) .^ 2 + 12 .* y_m(vecBI) .* eta_3(vecBI) - 12 .* z_m(vecBI) .^ 2) .* xi_3(vecBI) - 12 .* x_m(vecBI) .* (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_3(vecBI))) .* xi_2(vecBI) + (6 .* eta_2(vecBI) .^ 2 - 12 .* y_m(vecBI) .* eta_2(vecBI) + 6 .* y_m(vecBI) .^ 2 + 6 .* z_m(vecBI) .^ 2) .* xi_3(vecBI) .^ 2 + 12 .* (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_2(vecBI)) .* x_m(vecBI) .* xi_3(vecBI) + 6 .* (eta_2(vecBI) - eta_3(vecBI)) .^ 2 .* (x_m(vecBI) .^ 2 + z_m(vecBI) .^ 2));
    tmp34 = (-xi_3(vecBI) + xi_2(vecBI)) .* (xi_2(vecBI) + xi_3(vecBI)) .* ((-y_m(vecBI) + eta_3(vecBI)) .* xi_2(vecBI) + (y_m(vecBI) - eta_2(vecBI)) .* xi_3(vecBI) + x_m(vecBI) .* (eta_2(vecBI) - eta_3(vecBI))) .* ((eta_3(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_3(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_3(vecBI) + xi_3(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2) .^ (-0.1e1 ./ 0.2e1)) .* (((xi_3(vecBI) - x_m(vecBI)) .* xi_2(vecBI) - xi_3(vecBI) .^ 2 + x_m(vecBI) .* xi_3(vecBI) - (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_3(vecBI))) .* sqrt((eta_2(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_2(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_2(vecBI) + xi_2(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2)) + (-xi_2(vecBI) .^ 2 + (xi_3(vecBI) + x_m(vecBI)) .* xi_2(vecBI) - x_m(vecBI) .* xi_3(vecBI) + (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_2(vecBI))) .* sqrt((eta_3(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_3(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_3(vecBI) + xi_3(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2))) .* ((eta_2(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_2(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_2(vecBI) + xi_2(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2) .^ (-0.1e1 ./ 0.2e1)) ./ ((2 .* eta_3(vecBI) .^ 2 - 4 .* y_m(vecBI) .* eta_3(vecBI) + 2 .* y_m(vecBI) .^ 2 + 2 .* z_m(vecBI) .^ 2) .* xi_2(vecBI) .^ 2 + (((4 .* y_m(vecBI) - 4 .* eta_3(vecBI)) .* eta_2(vecBI) - 4 .* y_m(vecBI) .^ 2 + 4 .* y_m(vecBI) .* eta_3(vecBI) - 4 .* z_m(vecBI) .^ 2) .* xi_3(vecBI) - 4 .* x_m(vecBI) .* (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_3(vecBI))) .* xi_2(vecBI) + (2 .* eta_2(vecBI) .^ 2 - 4 .* y_m(vecBI) .* eta_2(vecBI) + 2 .* y_m(vecBI) .^ 2 + 2 .* z_m(vecBI) .^ 2) .* xi_3(vecBI) .^ 2 + 4 .* (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_2(vecBI)) .* x_m(vecBI) .* xi_3(vecBI) + 2 .* (eta_2(vecBI) - eta_3(vecBI)) .^ 2 .* (x_m(vecBI) .^ 2 + z_m(vecBI) .^ 2));
    tmp35 = -0.2e1 .* ((eta_3(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_3(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_3(vecBI) + xi_3(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2) .^ (-0.1e1 ./ 0.2e1)) .* (-xi_3(vecBI) + xi_2(vecBI)) .* ((C(vecBI) .* xi_2(vecBI) .^ 2) + ((C(vecBI) .* xi_3(vecBI)) + 0.3e1 ./ 0.2e1 .* D_LE(vecBI)) .* xi_2(vecBI) + xi_3(vecBI) .* ((C(vecBI) .* xi_3(vecBI)) + 0.3e1 ./ 0.2e1 .* D_LE(vecBI))) .* (((x_m(vecBI) - xi_3(vecBI)) .* xi_2(vecBI) + xi_3(vecBI) .^ 2 - x_m(vecBI) .* xi_3(vecBI) + (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_3(vecBI))) .* sqrt((eta_2(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_2(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_2(vecBI) + xi_2(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2)) - (-xi_2(vecBI) .^ 2 + (xi_3(vecBI) + x_m(vecBI)) .* xi_2(vecBI) - x_m(vecBI) .* xi_3(vecBI) + (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_2(vecBI))) .* sqrt((eta_3(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_3(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_3(vecBI) + xi_3(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2))) .* ((eta_2(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_2(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_2(vecBI) + xi_2(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2) .^ (-0.1e1 ./ 0.2e1)) .* ((-y_m(vecBI) + eta_3(vecBI)) .* xi_2(vecBI) + (y_m(vecBI) - eta_2(vecBI)) .* xi_3(vecBI) + x_m(vecBI) .* (eta_2(vecBI) - eta_3(vecBI))) ./ ((6 .* eta_3(vecBI) .^ 2 - 12 .* y_m(vecBI) .* eta_3(vecBI) + 6 .* y_m(vecBI) .^ 2 + 6 .* z_m(vecBI) .^ 2) .* xi_2(vecBI) .^ 2 + (((12 .* y_m(vecBI) - 12 .* eta_3(vecBI)) .* eta_2(vecBI) - 12 .* y_m(vecBI) .^ 2 + 12 .* y_m(vecBI) .* eta_3(vecBI) - 12 .* z_m(vecBI) .^ 2) .* xi_3(vecBI) - 12 .* x_m(vecBI) .* (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_3(vecBI))) .* xi_2(vecBI) + (6 .* eta_2(vecBI) .^ 2 - 12 .* y_m(vecBI) .* eta_2(vecBI) + 6 .* y_m(vecBI) .^ 2 + 6 .* z_m(vecBI) .^ 2) .* xi_3(vecBI) .^ 2 + 12 .* (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_2(vecBI)) .* x_m(vecBI) .* xi_3(vecBI) + 6 .* (eta_2(vecBI) - eta_3(vecBI)) .^ 2 .* (x_m(vecBI) .^ 2 + z_m(vecBI) .^ 2));
    tmp36 = (-xi_3(vecBI) + xi_2(vecBI)) .* ((-y_m(vecBI) + eta_3(vecBI)) .* xi_2(vecBI) + (y_m(vecBI) - eta_2(vecBI)) .* xi_3(vecBI) + x_m(vecBI) .* (eta_2(vecBI) - eta_3(vecBI))) .* ((eta_3(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_3(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_3(vecBI) + xi_3(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2) .^ (-0.1e1 ./ 0.2e1)) .* (((xi_3(vecBI) - x_m(vecBI)) .* xi_2(vecBI) - xi_3(vecBI) .^ 2 + x_m(vecBI) .* xi_3(vecBI) - (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_3(vecBI))) .* sqrt((eta_2(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_2(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_2(vecBI) + xi_2(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2)) + (-xi_2(vecBI) .^ 2 + (xi_3(vecBI) + x_m(vecBI)) .* xi_2(vecBI) - x_m(vecBI) .* xi_3(vecBI) + (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_2(vecBI))) .* sqrt((eta_3(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_3(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_3(vecBI) + xi_3(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2))) .* ((eta_2(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_2(vecBI) + x_m(vecBI) .^ 2 - 2 .* x_m(vecBI) .* xi_2(vecBI) + xi_2(vecBI) .^ 2 + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2) .^ (-0.1e1 ./ 0.2e1)) ./ ((eta_3(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_3(vecBI) + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2) .* xi_2(vecBI) .^ 2 + (((2 .* y_m(vecBI) - 2 .* eta_3(vecBI)) .* eta_2(vecBI) - 2 .* y_m(vecBI) .^ 2 + 2 .* y_m(vecBI) .* eta_3(vecBI) - 2 .* z_m(vecBI) .^ 2) .* xi_3(vecBI) - 2 .* x_m(vecBI) .* (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_3(vecBI))) .* xi_2(vecBI) + (eta_2(vecBI) .^ 2 - 2 .* y_m(vecBI) .* eta_2(vecBI) + y_m(vecBI) .^ 2 + z_m(vecBI) .^ 2) .* xi_3(vecBI) .^ 2 + 2 .* (eta_2(vecBI) - eta_3(vecBI)) .* (y_m(vecBI) - eta_2(vecBI)) .* x_m(vecBI) .* xi_3(vecBI) + (eta_2(vecBI) - eta_3(vecBI)) .^ 2 .* (x_m(vecBI) .^ 2 + z_m(vecBI) .^ 2));
    
    eps = 1e-5;
    r1 = [xi_2(vecBI) eta_2(vecBI) xi_2(vecBI).*0] - [x_m(vecBI) y_m(vecBI) z_m(vecBI)];
    r2 = [xi_3(vecBI) eta_3(vecBI) xi_3(vecBI).*0] - [x_m(vecBI) y_m(vecBI) z_m(vecBI)];
    idx_corr = sqrt(sum(r1.^2,2)) < eps | sqrt(sum(r2.^2,2)) < eps | sqrt(sum(cross(r1,r2,2).^2,2)) < eps;
    
    tmp11(idx_corr) = tmp11(idx_corr).*0;
    tmp12(idx_corr) = tmp11(idx_corr).*0;
    tmp13(idx_corr) = tmp11(idx_corr).*0;
    tmp14(idx_corr) = tmp11(idx_corr).*0;
    tmp15(idx_corr) = tmp11(idx_corr).*0;
    tmp16(idx_corr) = tmp11(idx_corr).*0;
    tmp21(idx_corr) = tmp11(idx_corr).*0;
    tmp22(idx_corr) = tmp11(idx_corr).*0;
    tmp23(idx_corr) = tmp11(idx_corr).*0;
    tmp24(idx_corr) = tmp11(idx_corr).*0;
    tmp25(idx_corr) = tmp11(idx_corr).*0;
    tmp26(idx_corr) = tmp11(idx_corr).*0;
    tmp31(idx_corr) = tmp11(idx_corr).*0;
    tmp32(idx_corr) = tmp11(idx_corr).*0;
    tmp33(idx_corr) = tmp11(idx_corr).*0;
    tmp34(idx_corr) = tmp11(idx_corr).*0;
    tmp35(idx_corr) = tmp11(idx_corr).*0;
    tmp36(idx_corr) = tmp11(idx_corr).*0;
    
end

%%
infl_new(1,1,:) = reshape(tmp11,1,1,[]);
infl_new(1,2,:) = reshape(tmp12,1,1,[]);
infl_new(1,3,:) = reshape(tmp13,1,1,[]);
infl_new(1,4,:) = reshape(tmp14,1,1,[]);
infl_new(1,5,:) = reshape(tmp15,1,1,[]);
infl_new(1,6,:) = reshape(tmp16,1,1,[]);

infl_new(2,1,:) = reshape(tmp21,1,1,[]);
infl_new(2,2,:) = reshape(tmp22,1,1,[]);
infl_new(2,3,:) = reshape(tmp23,1,1,[]);
infl_new(2,4,:) = reshape(tmp24,1,1,[]);
infl_new(2,5,:) = reshape(tmp25,1,1,[]);
infl_new(2,6,:) = reshape(tmp26,1,1,[]);

infl_new(3,1,:) = reshape(tmp31,1,1,[]);
infl_new(3,2,:) = reshape(tmp32,1,1,[]);
infl_new(3,3,:) = reshape(tmp33,1,1,[]);
infl_new(3,4,:) = reshape(tmp34,1,1,[]);
infl_new(3,5,:) = reshape(tmp35,1,1,[]);
infl_new(3,6,:) = reshape(tmp36,1,1,[]);

%%
infl_loc = real(infl_new);
% infl_loc(:,:,idx_flp) = -infl_loc(:,:,idx_flp);

idx_nan = find(reshape(sum(any(isnan(infl_new) | isinf(infl_new))),[],1) > 0);
if any(idx_nan)
%     disp('Nan induction in fcnHDVEIND_DB');
end
infl_loc(isnan(infl_loc) | isinf(infl_loc)) = 0;

% infl_loc(1:2,:,idx_afx) = infl_loc(1:2,:,idx_afx).*reshape((z_m_orig./ztol),1,1,[]);

end