function q = trcomp(A1,A2,B1,B2,C2,eta_p,xi_p,zeta_p, eta_1, eta_2, eta_3, xi_1, xi_2, xi_3)
%TRCOMP
%    TR = TRCOMP(A1,A2,B1,B2,C2,ETA,ETA_P,XI,XI_P,ZETA_P)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    12-Mar-2018 12:42:12

% x = xi
% y = eta
syms x y

t2 = abs(zeta_p);
t6 = y-eta_p;
t3 = abs(t6);
t8 = x-xi_p;
t4 = abs(t8);
t5 = t2.^2;
t7 = t3.^2;
t9 = t4.^2;
t10 = t5+t7+t9;
t11 = 1.0./t10.^(3.0./2.0);
t12 = A1.*y;
t13 = C2.*x;
t14 = A2+t12+t13;
t15 = C2.*y;
t16 = B1.*x;
t17 = B2+t15+t16;
tr = [-t11.*t17.*zeta_p,-t11.*t14.*zeta_p,-t11.*(t6.*t14+t8.*t17)];

eta_le = matlabFunction(eta_2 + (x - xi_2)*((eta_3 - eta_2)/(xi_3 - xi_2)));
eta_te = matlabFunction(eta_1 + (x - xi_1)*((eta_3 - eta_1)/(xi_3 - xi_1)));

% tr2 = matlabFunction(tr);
q = zeros(1,3);

if isempty(find(tr(1) == 0,1))
    q(:,1) = integral2(matlabFunction(tr(1)), xi_1, xi_3, eta_te, eta_le);
end

if isempty(find(tr(2) == 0))
    q(:,2) = integral2(matlabFunction(tr(2)), xi_1, xi_3, eta_te, eta_le);
end

if isempty(find(tr(3) == 0))
    q(:,3) = integral2(matlabFunction(tr(3)), xi_1, xi_3, eta_te, eta_le);
end   

end
