function out1 = w_zeta(A1,A2,B1,B2,C2,eta_1,eta_2,eta_3,eta_p,xi_1,xi_3,xi_p,zeta_p)
%W_ZETA
%    OUT1 = W_ZETA(A1,A2,B1,B2,C2,ETA_1,ETA_2,ETA_3,ETA_P,XI_1,XI_3,XI_P,ZETA_P)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    07-Mar-2018 02:39:58

out1 = 1.0./abs(zeta_p).^3.*(eta_1-eta_2).*(xi_1-xi_3).*(A2.*eta_1.*2.0+A2.*eta_2.*2.0+A2.*eta_3.*2.0-A2.*eta_p.*6.0+B2.*xi_1.*4.0+B2.*xi_3.*2.0-B2.*xi_p.*6.0+A1.*eta_1.^2+A1.*eta_2.^2+A1.*eta_3.^2+B1.*xi_1.^2.*3.0+B1.*xi_3.^2+A1.*eta_1.*eta_2+A1.*eta_1.*eta_3+A1.*eta_2.*eta_3-A1.*eta_1.*eta_p.*2.0-A1.*eta_2.*eta_p.*2.0-A1.*eta_3.*eta_p.*2.0+C2.*eta_1.*xi_1.*3.0+C2.*eta_2.*xi_1.*3.0+C2.*eta_1.*xi_3+C2.*eta_3.*xi_1.*2.0+C2.*eta_2.*xi_3+C2.*eta_3.*xi_3.*2.0-C2.*eta_1.*xi_p.*2.0-C2.*eta_p.*xi_1.*4.0-C2.*eta_2.*xi_p.*2.0-C2.*eta_3.*xi_p.*2.0-C2.*eta_p.*xi_3.*2.0+B1.*xi_1.*xi_3.*2.0-B1.*xi_1.*xi_p.*4.0-B1.*xi_3.*xi_p.*2.0).*(-1.0./1.2e1);
