function I = fcnK1(S, t, u, alpha, F, tol, idx) 
len = size(S,1);
I = nan(len,2);
 
idx_tmp = logical(idx(:,:,1));
I(idx_tmp) = fcnK1A(S(idx_tmp), t(idx_tmp), u(idx_tmp), alpha(idx_tmp), reshape(F(idx_tmp(:,:,[1,1])),[],1,2), tol); 
idx_tmp = logical(idx(:,:,2));
I(idx_tmp) = fcnK1B(S(idx_tmp), t(idx_tmp), u(idx_tmp), alpha(idx_tmp), reshape(F(idx_tmp(:,:,[1,1])),[],1,2), tol); 
idx_tmp = logical(idx(:,:,3));
I(idx_tmp) = fcnK1C(S(idx_tmp), t(idx_tmp), u(idx_tmp), alpha(idx_tmp), reshape(F(idx_tmp(:,:,[1,1])),[],1,2), tol); 
idx_tmp = logical(idx(:,:,4));
I(idx_tmp) = fcnK1D(S(idx_tmp), t(idx_tmp), u(idx_tmp), alpha(idx_tmp), reshape(F(idx_tmp(:,:,[1,1])),[],1,2), tol); 
idx_tmp = logical(idx(:,:,5));
I(idx_tmp) = fcnK1E(S(idx_tmp), t(idx_tmp), u(idx_tmp), alpha(idx_tmp), reshape(F(idx_tmp(:,:,[1,1])),[],1,2), tol); 
idx_tmp = logical(idx(:,:,6));
I(idx_tmp) = fcnK1F(S(idx_tmp), t(idx_tmp), u(idx_tmp), alpha(idx_tmp), reshape(F(idx_tmp(:,:,[1,1])),[],1,2), tol); 
idx_tmp = logical(idx(:,:,7));
I(idx_tmp) = fcnK1G(S(idx_tmp), t(idx_tmp), u(idx_tmp), alpha(idx_tmp), reshape(F(idx_tmp(:,:,[1,1])),[],1,2), tol); 
idx_tmp = logical(idx(:,:,8));
I(idx_tmp) = fcnK1H(S(idx_tmp), t(idx_tmp), u(idx_tmp), alpha(idx_tmp), reshape(F(idx_tmp(:,:,[1,1])),[],1,2), tol); 
idx_tmp = logical(idx(:,:,9));
I(idx_tmp) = fcnK1I(S(idx_tmp), t(idx_tmp), u(idx_tmp), alpha(idx_tmp), reshape(F(idx_tmp(:,:,[1,1])),[],1,2), tol); 
idx_tmp = logical(idx(:,:,10));
I(idx_tmp) = fcnK1J(S(idx_tmp), t(idx_tmp), u(idx_tmp), alpha(idx_tmp), reshape(F(idx_tmp(:,:,[1,1])),[],1,2), tol); 
idx_tmp = logical(idx(:,:,11));
I(idx_tmp) = fcnK1K(S(idx_tmp), t(idx_tmp), u(idx_tmp), alpha(idx_tmp), reshape(F(idx_tmp(:,:,[1,1])),[],1,2), tol); 
idx_tmp = logical(idx(:,:,12));
I(idx_tmp) = fcnK1L(S(idx_tmp), t(idx_tmp), u(idx_tmp), alpha(idx_tmp), reshape(F(idx_tmp(:,:,[1,1])),[],1,2), tol); 
idx_tmp = logical(idx(:,:,13));
I(idx_tmp) = fcnK1M(S(idx_tmp), t(idx_tmp), u(idx_tmp), alpha(idx_tmp), reshape(F(idx_tmp(:,:,[1,1])),[],1,2), tol); 
idx_tmp = logical(idx(:,:,14));
I(idx_tmp) = fcnK1N(S(idx_tmp), t(idx_tmp), u(idx_tmp), alpha(idx_tmp), reshape(F(idx_tmp(:,:,[1,1])),[],1,2), tol); 
idx_tmp = logical(idx(:,:,15));
I(idx_tmp) = fcnK1O(S(idx_tmp), t(idx_tmp), u(idx_tmp), alpha(idx_tmp), reshape(F(idx_tmp(:,:,[1,1])),[],1,2), tol); 
idx_tmp = logical(idx(:,:,16));
I(idx_tmp) = fcnK1P(S(idx_tmp), t(idx_tmp), u(idx_tmp), alpha(idx_tmp), reshape(F(idx_tmp(:,:,[1,1])),[],1,2), tol); 
idx_tmp = logical(idx(:,:,17));
I(idx_tmp) = fcnK1Q(S(idx_tmp), t(idx_tmp), u(idx_tmp), alpha(idx_tmp), reshape(F(idx_tmp(:,:,[1,1])),[],1,2), tol); 
idx_tmp = logical(idx(:,:,18));
I(idx_tmp) = fcnK1R(S(idx_tmp), t(idx_tmp), u(idx_tmp), alpha(idx_tmp), reshape(F(idx_tmp(:,:,[1,1])),[],1,2), tol); 
idx_tmp = logical(idx(:,:,19));
I(idx_tmp) = fcnK1S(S(idx_tmp), t(idx_tmp), u(idx_tmp), alpha(idx_tmp), reshape(F(idx_tmp(:,:,[1,1])),[],1,2), tol); 
idx_tmp = logical(idx(:,:,20));
I(idx_tmp) = fcnK1T(S(idx_tmp), t(idx_tmp), u(idx_tmp), alpha(idx_tmp), reshape(F(idx_tmp(:,:,[1,1])),[],1,2), tol); 

end
